services:

  api:
    build: ./api
    image: sc-api:latest
    labels:
      - "traefik.http.routers.scapi.rule=Host(`safe-api.pointbeing.net`)"
      - "traefik.http.routers.scapi.tls=true"
      - "traefik.http.routers.scapi.tls.certresolver=letsencrypt"
      - "traefik.http.services.scapi.loadbalancer.server.port=5010"
    networks:
      - traefik_default
    ports:
      - "5010:5010"
    restart: unless-stopped

  web:
    build: ./site
    image: sc-site:latest
    labels:
      - "traefik.http.routers.scweb.rule=Host(`safe.pointbeing.net`)"
      - "traefik.http.routers.scweb.tls=true"
      - "traefik.http.routers.scweb.tls.certresolver=letsencrypt"
      - "traefik.http.services.scweb.loadbalancer.server.port=5011"
    networks:
      - traefik_default
    ports:
      - "5011:5011"
    depends_on:
      - api
    restart: unless-stopped


networks:
  traefik_default:
    name: traefik_default
    external: true



  # traefik:
  #   image: traefik:v2.10
  #   command: --api.insecure=true --providers.docker
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
