server {
    listen 5011;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|jpg|jpeg|png|gif|ico)$ {
        try_files $uri =404;
    }
}